---
title: "DiD: Monte-Carlo Simulation"
author: "Daniel Redel"
format: html
editor: visual
---

# Model Comparison: Monte Carlo Simulation

Simulate data Following Sant'Anna and Zhao (2020)'s DGP 1

## Monte Carlo Results

```{r, include=FALSE}
rm(list=ls())
library(tidyverse)
library(kableExtra)
library(modelsummary)
library(fixest)
library(gtsummary)
library(did)
library(DRDID)
library(car)
library(ggpubr)
```

```{r}
## Simulate data Following Sant'Anna and Zhao (2020)'s DGP 1 (RC Case)

# Sample size
n <- 1000
# pscore index (strength of common support)
Xsi.ps <- .75
# Proportion in each period
lambda <- 0.5
# Researcher always observes Z
#-----------------------------------------------------------------------------
set.seed(1234)
# Gen covariates
x1 <- stats::rnorm(n, mean = 0, sd = 1)
x2 <- stats::rnorm(n, mean = 0, sd = 1)
x3 <- stats::rnorm(n, mean = 0, sd = 1)
x4 <- stats::rnorm(n, mean = 0, sd = 1)

x <- cbind(x1, x2, x3, x4)
#-----------------------------------------------------------------------------
# Gen treatment groups
# Propensity score
pi <- stats::plogis(Xsi.ps * (- x1 + 0.5 * x2 - 0.25 * x3 - 0.1 * x4))
d  <- as.numeric(runif(n) <= pi)
#-----------------------------------------------------------------------------
# Generate aux indexes for the potential outcomes
index.lin <- 210 + 27.4*x1 + 13.7*(x2 + x3 + x4)
index.unobs.het <- d * (index.lin)
index.att <- 0

#This is the key for consistency of outcome regression
index.trend <- 210 + 27.4*x1 + 13.7*(x2 + x3 + x4)

#v is the unobserved heterogeneity
v <- stats::rnorm(n, mean = index.unobs.het, sd = 1)

#Gen realized outcome at time 0
y0 <- index.lin + v + stats::rnorm(n)

# gen outcomes at time 1
# First let's generate potential outcomes: y_1_potential
y10 <- index.lin + v + stats::rnorm(n, mean = 0, sd = 1) +#This is the baseline
  index.trend #this is for the trend based on X

y11 <- index.lin + v + stats::rnorm(n, mean = 0, sd = 1) +#This is the baseline
  index.trend + #this is for the trend based on X
  index.att # This is the treatment effects

# Gen realized outcome at time 1
y1 <- d * y11 + (1 - d) * y10

# Generate "T"
post <- as.numeric(stats::runif(n) <= lambda)
# observed outcome
y <- post * y1 + (1 - post) * y0
#-----------------------------------------------------------------------------
#Gen id
id <- as.numeric(1:n)
#-----------------------------------------------------------------------------
# Put in a long data frame
sim_rc1 <- as.data.frame(cbind(id = id, post = post, y = y, d = d,
                                x1 = x1, x2= x2, x3 = x3, x4 = x4))
sim_rc1 <- sim_rc[order(sim_rc$id),]
```

**TWFE Regression**:

```{r, cache=TRUE}
twfe_boots <- lm(y ~ post*d + x1 + x2 + x3 + x4, sim_rc1)
set.seed(12345)
betahat.boot <- Boot(twfe_boots, R=200)
```

```{r, include=FALSE}
twfe_plot <- data.frame(beta=betahat.boot$t[,8]) %>% 
  ggplot(aes(x = beta)) +
  geom_histogram(bins = 100, fill="orange") + 
  geom_vline(xintercept = mean(betahat.boot$t[,8]), linetype = 5) +
  labs(title="TWFE DiD") + xlim(-40,15) + theme_bw()
```

**OR-DID Estimator**:

```{r, cache=TRUE}
set.seed(12345)
or_estimator <- ordid(yname="y", tname = "post", idname = "id", dname = "d",
      xformla= ~ x1 + x2 + x3 + x4,
      data = sim_rc1, panel = FALSE,
      boot = TRUE, nboot = 200)
```

```{r, include=FALSE}
or_plot <- data.frame(beta=or_estimator$boots) %>% 
  ggplot(aes(x = beta)) +
  geom_histogram(bins = 100, fill="orange") + 
  geom_vline(xintercept = mean(or_estimator$boots), linetype = 5) +
  labs(title="OR DiD") + xlim(-40,15) + theme_bw()
```

**IPW-DID Estimator**:

```{r, cache=TRUE}
set.seed(12345)
ipw_estimator <- ipwdid(yname="y", tname = "post", idname = "id", dname = "d",
      xformla= ~ x1 + x2 + x3 + x4,
      data = sim_rc1, panel = FALSE,
      boot = TRUE, nboot = 200)
```

```{r, include=FALSE}
ipw_plot <- data.frame(beta=ipw_estimator$boots) %>% 
  ggplot(aes(x = beta)) +
  geom_histogram(bins = 100, fill="orange") + 
  geom_vline(xintercept = mean(ipw_estimator$boots), linetype = 5) +
  labs(title="IPW DiD") + xlim(-40,15) + theme_bw()
```

**DR-DID Estimator**:

```{r, cache=TRUE}
set.seed(12345)
dr_estimator <- drdid(yname="y", tname = "post", idname = "id", dname = "d",
      xformla= ~ x1 + x2 + x3 + x4,
      data = sim_rc1, panel = FALSE, estMethod = "trad", boot = TRUE, nboot = 200)
```

```{r, include=FALSE}
dr_plot <- data.frame(beta=dr_estimator$boots) %>% 
  ggplot(aes(x = beta)) +
  geom_histogram(bins = 100, fill="orange") + 
  geom_vline(xintercept = mean(dr_estimator$boots), linetype = 5) +
  labs(title="DR DiD") + xlim(-40,15) + theme_bw()
```

```{r, fig.align='center', message=FALSE, warning=FALSE, echo=FALSE}
#| label: fig-montecarlo1
#| fig-cap: "Monte-Carlo Results"
ggarrange(twfe_plot, or_plot, ipw_plot, dr_plot,
          ncol = 2, nrow = 2)
```
