// The industry study cases — Lyra sold as a SaaS across verticals. Each is a "protocol" (Eppo-style
// template): a business framing + the method + the DGP, with optional links to a live seeded experiment
// and a prefill for the create wizard. The briefs read like a short notebook.

export const STUDY_CASES = [
  {
    id: "reward-ua",
    industry: "Mobile adtech · Rewarded UA",
    accent: "#1E6091",
    title: "Reward sizing for rewarded user acquisition",
    question: "Does a bigger sign-up reward lift conversion — without blowing payout cost?",
    methods: ["A/B", "CUPED", "Guardrails"],
    result: "+25.7% conversion, certified — but it only ships if payout cost & D7 retention hold.",
    liveId: "exp_reward_a",
    template: { design: "ab", metric_type: "proportion", mu: 0.4, true_effect: 0.1, rel_mde: 0.05 },
    brief: {
      business: "A rewarded-UA marketplace (think Almedia / Freecash) pays users to complete advertiser offers; advertisers pay for the conversions. The lever under test is the size of the sign-up reward.",
      experiment: "Treatment shows a larger reward. The success metric is conversion rate; the guardrails are advertiser payout cost and D7 retention — the reward must not become unprofitable or attract users who churn.",
      whyHard: "A bigger reward can lift conversion while quietly hurting the business: it can attract reward-seekers who never retain, or cost more than the conversions are worth. A win on the primary alone is not a ship — the decision is a conjunction of primary + guardrails.",
      dgp: "Agents choose offers by a utility model; we set the true reward elasticity, so the real lift is known. That lets Lyra certify the estimate — a real platform only sees the noisy readout.",
      result: "Lyra estimates the lift, certifies its CI covers the known truth, and the decision rule ships only when the guardrails clear their non-inferiority margins.",
    },
  },
  {
    id: "surge-switchback",
    industry: "On-demand · Delivery / Rideshare",
    accent: "#0E7C6B",
    title: "Surge pricing, tested without breaking the market",
    question: "Does surge pricing raise GMV — when you can't A/B individual users?",
    methods: ["Switchback", "Cluster-robust", "CUPED"],
    result: "+3.7% GMV/period, certified — via a switchback, because a user-level A/B would be biased.",
    liveId: "exp_surge_switchback",
    template: { design: "switchback", mu: 2000, true_effect: 70, J: 55, H: 22, n_bar: 20 },
    brief: {
      business: "An on-demand delivery / rideshare marketplace. Pricing moves shared supply — couriers and drivers — so it can't be tested one user at a time.",
      experiment: "Toggle surge on and off over time within a market; the success metric is GMV per period.",
      whyHard: "Randomizing users violates SUTVA: a price change shifts shared supply, so a treated user's outcome depends on how many others are treated. Randomizing whole cities gives a sample size of ~2. A switchback holds the market fixed and randomizes over time — at the price of carryover and a power floor from macro shocks.",
      dgp: "A multi-shock time series with carryover; we author the true per-period effect τ, so the estimator can be graded against it.",
      result: "A switchback with CUPED + cluster-robust SEs recovers τ and certifies; the structural power floor (macro shocks don't average away) is visible in the design.",
    },
  },
  {
    id: "marketplace-cannibalization",
    industry: "Marketplace · Two-sided / shared budget",
    accent: "#9333A8",
    title: "Real lift, or just cannibalization?",
    question: "Does a promo create new conversions — or just steal them from elsewhere?",
    methods: ["Interference-aware", "Cluster randomization"],
    result: "Naive A/B says +0.33 (uncertified ✗); the cluster design says +0.078 (certified ✓) — the truth.",
    liveId: "exp_marketplace_cluster",
    template: { design: "interference", interference_design: "cluster", boost: 0.6, G: 40, n_g: 300 },
    brief: {
      business: "A two-sided marketplace with a shared budget — promotions, ad spend, reward pools. Treating more users draws down a common resource.",
      experiment: "A promo that lifts conversion; the success metric is the global conversion effect (all-treat vs all-control).",
      whyHard: "Treated users grab the shared budget and cannibalize the controls, so a naive user-level A/B over-states the effect 3–5× — and the estimate even drifts as you ramp the allocation, a tell-tale of interference. SUTVA is broken.",
      dgp: "Shared-budget cannibalization, with the true global effect authored, so each design can be graded against it.",
      result: "Lyra refuses to certify the naive design — its CI misses the truth — while the cluster-randomized design certifies. The platform catches a biased analysis before it ships.",
    },
  },
  {
    id: "checkout-feature",
    industry: "E-commerce · Feature change",
    accent: "#C2410C",
    title: "A checkout change — and the trust check that comes first",
    question: "Did the new checkout lift conversion — and can you even trust the readout?",
    methods: ["A/B", "SRM", "A/A", "Always-valid"],
    result: "The A/A correctly shows no effect — proof the pipeline doesn't manufacture false wins.",
    liveId: "exp_checkout_aa",
    template: { design: "ab", metric_type: "proportion", mu: 0.2, true_effect: 0.0, rel_mde: 0.05 },
    brief: {
      business: "An e-commerce store testing a checkout redesign — a classic product feature change.",
      experiment: "The new flow vs the old; the success metric is purchase conversion. But first: is the measurement itself trustworthy?",
      whyHard: "Two silent killers: peeking at results inflates false positives, and a broken randomizer (sample-ratio mismatch) biases everything. You prove the pipeline is trustworthy with an A/A test before you believe any A/B.",
      dgp: "We run an A/A (zero true effect) alongside real-effect variants, so the trust gates can be validated against the known truth.",
      result: "The SRM gate passes, the A/A reads 'no detectable change', and an always-valid confidence sequence lets you peek any time without inflating error. Trust first, then test.",
    },
  },
  {
    id: "ads-incrementality",
    industry: "Performance marketing · Ad incrementality",
    accent: "#B45309",
    title: "Does the ad cause conversions — or take credit for them?",
    question: "Most 'attributed' conversions would have happened anyway. What's the real lift?",
    methods: ["Ghost ads / PSA holdout", "ITT / CACE", "Real data (Criteo)"],
    result: "Naive attribution overstates ~6×; a holdout recovers the truth — validated on Criteo's 13.9M-row RCT (+1.06pp visits).",
    liveId: null,
    template: null,
    deepDive: true,
    brief: {
      business: "A performance-marketing team measuring whether ad spend actually drives conversions.",
      experiment: "Show the ad vs a PSA / ghost-ad holdout (the ad withheld, organic path intact); the metric is incremental conversions.",
      whyHard: "Naive attribution credits every conversion among the exposed to the ad — but most would have happened organically (Lewis–Rao). The true lift is small and easily faked; non-compliance (the ad doesn't always serve) means you must separate the effect of assignment (ITT) from the effect on the exposed (CACE).",
      dgp: "We author the organic conversion propensity and the true incremental τ, then check the holdout recovers it.",
      result: "The holdout ITT and CACE recover τ (naive attribution overstates ~6×) — and the same estimator on the real Criteo Uplift RCT gives a small, highly-significant +1.06pp visit lift. Validated at scale.",
    },
  },
  {
    id: "targeting-cate",
    industry: "Personalization · Targeting",
    accent: "#0F766E",
    title: "Who should we treat?",
    question: "The average effect is small — but who responds, and is targeting worth it?",
    methods: ["CATE", "Causal forest", "Uplift / RATE", "Policy"],
    result: "ATE +0.5 hides effects from −3 to +5; targeting the top responders is worth ~2.9× treat-all.",
    liveId: null,
    template: null,
    deepDive: true,
    brief: {
      business: "Personalizing an offer or treatment — spend the incentive only on the users it actually moves.",
      experiment: "Estimate the per-user effect τ(x), then learn a targeting policy and measure its value.",
      whyHard: "The average effect hides huge heterogeneity — here a third of users are actively harmed. You need trustworthy per-user effects, a deployable policy, and an honest estimate of that policy's value from logged data (off-policy evaluation).",
      dgp: "We author the true CATE surface τ(x), so both the CATE estimate and the policy value can be graded against ground truth.",
      result: "A causal forest's pointwise CIs cover the true τ(x); the targeting policy beats treat-all ~2.9× net of cost; and doubly-robust off-policy evaluation recovers the true policy value — tighter than IPS.",
    },
  },
];

export const BRIEF_SECTIONS = [
  ["business", "The business"],
  ["experiment", "The experiment"],
  ["whyHard", "Why it's hard"],
  ["dgp", "How we simulate it (the DGP)"],
  ["result", "What Lyra shows"],
];
